return {
	PlaceObj('ModItemFolder', {
		'name', "Items",
	}, {
		PlaceObj('ModItemFolder', {
			'name', "Armor",
		}, {
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Armor - Camo",
				'Id', "CamoArmor_Light_Kompositum",
				'object_class', "Armor",
				'ScrapParts', 4,
				'Degradation', 6,
				'Icon', "UI/Icons/Items/camo_armor_light",
				'SubIcon', "UI/Icons/Items/kompositum58.png",
				'DisplayName', T(397773868357, --[[ModItemInventoryItemCompositeDef CamoArmor_Light_Kompositum DisplayName]] "Kompositum Light Camo Armor"),
				'DisplayNamePlural', T(434942276692, --[[ModItemInventoryItemCompositeDef CamoArmor_Light_Kompositum DisplayNamePlural]] "Kompositum Light Camo Armors"),
				'AdditionalHint', T(746247256738, --[[ModItemInventoryItemCompositeDef CamoArmor_Light_Kompositum AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Harder to detect by enemies\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Aiming is less effective against camouflaged targets\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Combined with Kompositum 58"),
				'Cost', 4500,
				'Tier', 2,
				'MaxStock', 1,
				'RestockWeight', 25,
				'CategoryPair', "Light",
				'PenetrationClass', 3,
				'DamageReduction', 20,
				'AdditionalReduction', 35,
				'ProtectedBodyParts', set( "Torso" ),
				'Camouflage', true,
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Armor - Camo",
				'Id', "CamoArmor_Medium_Kompositum",
				'object_class', "Armor",
				'ScrapParts', 4,
				'Degradation', 6,
				'Icon', "UI/Icons/Items/camo_armor_medium",
				'SubIcon', "UI/Icons/Items/kompositum58.png",
				'DisplayName', T(463744891017, --[[ModItemInventoryItemCompositeDef CamoArmor_Medium_Kompositum DisplayName]] "Kompositum Medium Camo Armor"),
				'DisplayNamePlural', T(484875824354, --[[ModItemInventoryItemCompositeDef CamoArmor_Medium_Kompositum DisplayNamePlural]] "Kompositum Medium Camo Armors"),
				'AdditionalHint', T(819874021257, --[[ModItemInventoryItemCompositeDef CamoArmor_Medium_Kompositum AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Harder to detect by enemies\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Aiming is less effective against camouflaged targets\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Combined with Kompositum 58"),
				'Cost', 9000,
				'Tier', 3,
				'MaxStock', 1,
				'RestockWeight', 25,
				'CategoryPair', "Medium",
				'PenetrationClass', 4,
				'DamageReduction', 20,
				'AdditionalReduction', 45,
				'ProtectedBodyParts', set( "Torso" ),
				'Camouflage', true,
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Armor - Flak",
				'Id', "FlakArmor_Kompositum",
				'object_class', "Armor",
				'ScrapParts', 4,
				'Degradation', 6,
				'Icon', "UI/Icons/Items/flak_armor",
				'SubIcon', "UI/Icons/Items/kompositum58.png",
				'DisplayName', T(357033398380, --[[ModItemInventoryItemCompositeDef FlakArmor_Kompositum DisplayName]] "Kompositum Flak Armor"),
				'DisplayNamePlural', T(911458048470, --[[ModItemInventoryItemCompositeDef FlakArmor_Kompositum DisplayNamePlural]] "Kompositum Flak Armors"),
				'AdditionalHint', T(248245180526, --[[ModItemInventoryItemCompositeDef FlakArmor_Kompositum AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Combined with Kompositum 58"),
				'Cost', 1200,
				'MaxStock', 2,
				'RestockWeight', 75,
				'CategoryPair', "Light",
				'PenetrationClass', 3,
				'DamageReduction', 20,
				'AdditionalReduction', 35,
				'ProtectedBodyParts', set( "Arms", "Torso" ),
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Armor - Flak",
				'Id', "FlakLeggings_Kompositum",
				'object_class', "Armor",
				'ScrapParts', 4,
				'Degradation', 6,
				'Icon', "UI/Icons/Items/flak_leggings",
				'SubIcon', "UI/Icons/Items/kompositum58.png",
				'DisplayName', T(319270529401, --[[ModItemInventoryItemCompositeDef FlakLeggings_Kompositum DisplayName]] "Kompositum Flak Leggings"),
				'DisplayNamePlural', T(163519475788, --[[ModItemInventoryItemCompositeDef FlakLeggings_Kompositum DisplayNamePlural]] "Kompositum Flak Leggings"),
				'AdditionalHint', T(333246943566, --[[ModItemInventoryItemCompositeDef FlakLeggings_Kompositum AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Combined with Kompositum 58"),
				'Cost', 800,
				'RestockWeight', 35,
				'CategoryPair', "Light",
				'Slot', "Legs",
				'PenetrationClass', 3,
				'DamageReduction', 20,
				'AdditionalReduction', 35,
				'ProtectedBodyParts', set( "Groin", "Legs" ),
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Armor - Flak",
				'Id', "FlakVest_Kompositum",
				'object_class', "Armor",
				'ScrapParts', 4,
				'Degradation', 6,
				'Icon', "UI/Icons/Items/flak_vest",
				'SubIcon', "UI/Icons/Items/kompositum58.png",
				'DisplayName', T(656361393769, --[[ModItemInventoryItemCompositeDef FlakVest_Kompositum DisplayName]] "Kompositum Flak Vest"),
				'DisplayNamePlural', T(410366299207, --[[ModItemInventoryItemCompositeDef FlakVest_Kompositum DisplayNamePlural]] "Kompositum Flak Vests"),
				'AdditionalHint', T(149791564320, --[[ModItemInventoryItemCompositeDef FlakVest_Kompositum AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Combined with Kompositum 58"),
				'Cost', 800,
				'RestockWeight', 75,
				'CategoryPair', "Light",
				'PenetrationClass', 3,
				'DamageReduction', 20,
				'AdditionalReduction', 35,
				'ProtectedBodyParts', set( "Torso" ),
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Armor - Heavy",
				'Id', "HeavyArmorChestplate_Kompositum",
				'object_class', "Armor",
				'ScrapParts', 4,
				'Degradation', 6,
				'Icon', "UI/Icons/Items/heavy_vest",
				'SubIcon', "UI/Icons/Items/kompositum58.png",
				'DisplayName', T(345146671178, --[[ModItemInventoryItemCompositeDef HeavyArmorChestplate_Kompositum DisplayName]] "Kompositum Heavy Vest"),
				'DisplayNamePlural', T(862783395639, --[[ModItemInventoryItemCompositeDef HeavyArmorChestplate_Kompositum DisplayNamePlural]] "Kompositum Heavy Vests"),
				'AdditionalHint', T(361655886922, --[[ModItemInventoryItemCompositeDef HeavyArmorChestplate_Kompositum AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Cumbersome (no Free Move)\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Combined with Kompositum 58"),
				'Cumbersome', 1,
				'Valuable', 1,
				'Cost', 4300,
				'Tier', 3,
				'RestockWeight', 50,
				'CategoryPair', "Heavy",
				'PenetrationClass', 5,
				'DamageReduction', 20,
				'AdditionalReduction', 55,
				'ProtectedBodyParts', set( "Torso" ),
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Armor - Heavy",
				'Id', "HeavyArmorHelmet_Kompositum",
				'object_class', "Armor",
				'ScrapParts', 2,
				'Degradation', 6,
				'Icon', "UI/Icons/Items/heavy_helmet",
				'SubIcon', "UI/Icons/Items/kompositum58.png",
				'DisplayName', T(925382457624, --[[ModItemInventoryItemCompositeDef HeavyArmorHelmet_Kompositum DisplayName]] "Kompositum Heavy Armor Helmet"),
				'DisplayNamePlural', T(622604677154, --[[ModItemInventoryItemCompositeDef HeavyArmorHelmet_Kompositum DisplayNamePlural]] "Kompositum Heavy Armor Helmets"),
				'AdditionalHint', T(364260940396, --[[ModItemInventoryItemCompositeDef HeavyArmorHelmet_Kompositum AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Cumbersome (no Free Move)\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Combined with Kompositum 58"),
				'Cumbersome', 1,
				'Valuable', 1,
				'Cost', 5000,
				'Tier', 3,
				'RestockWeight', 25,
				'CategoryPair', "Heavy",
				'Slot', "Head",
				'PenetrationClass', 5,
				'DamageReduction', 20,
				'AdditionalReduction', 55,
				'ProtectedBodyParts', set( "Head" ),
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Armor - Heavy",
				'Id', "HeavyArmorLeggings_Kompositum",
				'object_class', "Armor",
				'ScrapParts', 4,
				'Degradation', 6,
				'Icon', "UI/Icons/Items/heavy_leggings",
				'SubIcon', "UI/Icons/Items/kompositum58.png",
				'DisplayName', T(394243110114, --[[ModItemInventoryItemCompositeDef HeavyArmorLeggings_Kompositum DisplayName]] "Kompositum Heavy Armor Leggings"),
				'DisplayNamePlural', T(639883367049, --[[ModItemInventoryItemCompositeDef HeavyArmorLeggings_Kompositum DisplayNamePlural]] "Kompositum Heavy Armor Leggings"),
				'AdditionalHint', T(924789904007, --[[ModItemInventoryItemCompositeDef HeavyArmorLeggings_Kompositum AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Cumbersome (no Free Move)\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Combined with Kompositum 58"),
				'Cumbersome', 1,
				'Valuable', 1,
				'Cost', 4300,
				'Tier', 3,
				'RestockWeight', 25,
				'CategoryPair', "Heavy",
				'Slot', "Legs",
				'PenetrationClass', 5,
				'DamageReduction', 20,
				'AdditionalReduction', 55,
				'ProtectedBodyParts', set( "Groin", "Legs" ),
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Armor - Heavy",
				'Id', "HeavyArmorTorso_Kompositum",
				'object_class', "Armor",
				'ScrapParts', 4,
				'Degradation', 6,
				'Icon', "UI/Icons/Items/heavy_armor",
				'SubIcon', "UI/Icons/Items/kompositum58.png",
				'DisplayName', T(124355079245, --[[ModItemInventoryItemCompositeDef HeavyArmorTorso_Kompositum DisplayName]] "Kompositum Heavy Armor"),
				'DisplayNamePlural', T(587537247525, --[[ModItemInventoryItemCompositeDef HeavyArmorTorso_Kompositum DisplayNamePlural]] "Kompositum Heavy Armors"),
				'AdditionalHint', T(324491031177, --[[ModItemInventoryItemCompositeDef HeavyArmorTorso_Kompositum AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Cumbersome (no Free Move)\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Combined with Kompositum 58"),
				'Cumbersome', 1,
				'Valuable', 1,
				'Cost', 5500,
				'Tier', 2,
				'MaxStock', 2,
				'RestockWeight', 50,
				'CategoryPair', "Heavy",
				'PenetrationClass', 5,
				'DamageReduction', 20,
				'AdditionalReduction', 55,
				'ProtectedBodyParts', set( "Arms", "Torso" ),
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Armor - Kevlar",
				'Id', "KevlarChestplate_Kompositum",
				'object_class', "Armor",
				'ScrapParts', 4,
				'Degradation', 6,
				'Icon', "UI/Icons/Items/kevlar_vest",
				'SubIcon', "UI/Icons/Items/kompositum58.png",
				'DisplayName', T(990345792758, --[[ModItemInventoryItemCompositeDef KevlarChestplate_Kompositum DisplayName]] "Kompositum Kevlar Vest"),
				'DisplayNamePlural', T(992352620247, --[[ModItemInventoryItemCompositeDef KevlarChestplate_Kompositum DisplayNamePlural]] "Kompositum Kevlar Vests"),
				'AdditionalHint', T(312200087410, --[[ModItemInventoryItemCompositeDef KevlarChestplate_Kompositum AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Combined with Kompositum 58"),
				'Cost', 1400,
				'Tier', 2,
				'RestockWeight', 50,
				'CategoryPair', "Medium",
				'PenetrationClass', 4,
				'DamageReduction', 20,
				'AdditionalReduction', 45,
				'ProtectedBodyParts', set( "Torso" ),
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Armor - Kevlar",
				'Id', "KevlarHelmet_Kompositum",
				'object_class', "Armor",
				'ScrapParts', 2,
				'Degradation', 6,
				'Icon', "UI/Icons/Items/kevlar_helmet",
				'SubIcon', "UI/Icons/Items/kompositum58.png",
				'DisplayName', T(368375824009, --[[ModItemInventoryItemCompositeDef KevlarHelmet_Kompositum DisplayName]] "Kompositum Kevlar Helmet"),
				'DisplayNamePlural', T(878251772028, --[[ModItemInventoryItemCompositeDef KevlarHelmet_Kompositum DisplayNamePlural]] "Kompositum Kevlar Helmets"),
				'AdditionalHint', T(315828085760, --[[ModItemInventoryItemCompositeDef KevlarHelmet_Kompositum AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Combined with Kompositum 58"),
				'Cost', 1800,
				'Tier', 2,
				'RestockWeight', 25,
				'CategoryPair', "Medium",
				'Slot', "Head",
				'PenetrationClass', 4,
				'DamageReduction', 20,
				'AdditionalReduction', 45,
				'ProtectedBodyParts', set( "Head" ),
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Armor - Kevlar",
				'Id', "KevlarLeggings_Kompositum",
				'object_class', "Armor",
				'ScrapParts', 4,
				'Degradation', 6,
				'Icon', "UI/Icons/Items/kevlar_leggings",
				'SubIcon', "UI/Icons/Items/kompositum58.png",
				'DisplayName', T(367944064513, --[[ModItemInventoryItemCompositeDef KevlarLeggings_Kompositum DisplayName]] "Kompositum Kevlar Leggings"),
				'DisplayNamePlural', T(879232412097, --[[ModItemInventoryItemCompositeDef KevlarLeggings_Kompositum DisplayNamePlural]] "Kompositum Kevlar Leggings"),
				'AdditionalHint', T(250626032092, --[[ModItemInventoryItemCompositeDef KevlarLeggings_Kompositum AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Combined with Kompositum 58"),
				'Cost', 1400,
				'Tier', 2,
				'RestockWeight', 25,
				'CategoryPair', "Medium",
				'Slot', "Legs",
				'PenetrationClass', 4,
				'DamageReduction', 20,
				'AdditionalReduction', 45,
				'ProtectedBodyParts', set( "Groin", "Legs" ),
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Armor - Kevlar",
				'Id', "KevlarVest_Kompositum",
				'object_class', "Armor",
				'ScrapParts', 4,
				'Degradation', 6,
				'Icon', "UI/Icons/Items/kevlar_armor",
				'SubIcon', "UI/Icons/Items/kompositum58.png",
				'DisplayName', T(366789736680, --[[ModItemInventoryItemCompositeDef KevlarVest_Kompositum DisplayName]] "Kompositum Kevlar Armor"),
				'DisplayNamePlural', T(770481207060, --[[ModItemInventoryItemCompositeDef KevlarVest_Kompositum DisplayNamePlural]] "Kompositum Kevlar Armors"),
				'AdditionalHint', T(390031899678, --[[ModItemInventoryItemCompositeDef KevlarVest_Kompositum AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Combined with Kompositum 58"),
				'Cost', 2800,
				'Tier', 2,
				'MaxStock', 2,
				'RestockWeight', 50,
				'CategoryPair', "Medium",
				'PenetrationClass', 4,
				'DamageReduction', 20,
				'AdditionalReduction', 45,
				'ProtectedBodyParts', set( "Arms", "Torso" ),
			}),
			PlaceObj('ModItemInventoryItemCompositeDef', {
				'Group', "Armor - LightHelmet",
				'Id', "LightHelmet_Kompositum",
				'object_class', "Armor",
				'ScrapParts', 2,
				'Degradation', 8,
				'Icon', "UI/Icons/Items/light_helmet",
				'SubIcon', "UI/Icons/Items/kompositum58.png",
				'DisplayName', T(864227193170, --[[ModItemInventoryItemCompositeDef LightHelmet_Kompositum DisplayName]] "Kompositum Light Helmet"),
				'DisplayNamePlural', T(669481424311, --[[ModItemInventoryItemCompositeDef LightHelmet_Kompositum DisplayNamePlural]] "Kompositum Light Helmets"),
				'AdditionalHint', T(220514642282, --[[ModItemInventoryItemCompositeDef LightHelmet_Kompositum AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Combined with Kompositum 58"),
				'RestockWeight', 35,
				'CategoryPair', "Light",
				'Slot', "Head",
				'PenetrationClass', 3,
				'DamageReduction', 20,
				'AdditionalReduction', 35,
				'ProtectedBodyParts', set( "Head" ),
			}),
			}),
		}),
	PlaceObj('ModItemFolder', {
		'name', "Recipes",
	}, {
		PlaceObj('ModItemRecipeDef', {
			Difficulty = 70,
			ExplosivesRoll = true,
			Ingredients = {
				PlaceObj('RecipeIngredient', {
					'item', "Winchester1894",
				}),
				PlaceObj('RecipeIngredient', {
					'item', "Combination_Kompositum58",
				}),
			},
			MechanicalRoll = true,
			ResultItems = {
				PlaceObj('RecipeIngredient', {
					'item', "Winchester_Quest",
				}),
			},
			group = "Firearms",
			id = "Winchester",
		}),
		PlaceObj('ModItemRecipeDef', {
			Difficulty = 70,
			ExplosivesRoll = true,
			Ingredients = {
				PlaceObj('RecipeIngredient', {
					'item', "Auto5",
				}),
				PlaceObj('RecipeIngredient', {
					'item', "Combination_Kompositum58",
				}),
			},
			MechanicalRoll = true,
			ResultItems = {
				PlaceObj('RecipeIngredient', {
					'item', "Auto5_quest",
				}),
			},
			group = "Firearms",
			id = "Auto5",
		}),
		PlaceObj('ModItemRecipeDef', {
			Difficulty = 80,
			ExplosivesRoll = true,
			Ingredients = {
				PlaceObj('RecipeIngredient', {
					'item', "Galil",
				}),
				PlaceObj('RecipeIngredient', {
					'item', "Combination_Kompositum58",
				}),
			},
			MechanicalRoll = true,
			ResultItems = {
				PlaceObj('RecipeIngredient', {
					'item', "Galil_FlagHill",
				}),
			},
			group = "Firearms",
			id = "Galil",
		}),
		PlaceObj('ModItemRecipeDef', {
			Difficulty = 80,
			ExplosivesRoll = true,
			Ingredients = {
				PlaceObj('RecipeIngredient', {
					'item', "M24Sniper",
				}),
				PlaceObj('RecipeIngredient', {
					'item', "Combination_Kompositum58",
				}),
			},
			MechanicalRoll = true,
			ResultItems = {
				PlaceObj('RecipeIngredient', {
					'item', "GoldenGun",
				}),
			},
			group = "Firearms",
			id = "M24",
		}),
		PlaceObj('ModItemRecipeDef', {
			Difficulty = 80,
			ExplosivesRoll = true,
			Ingredients = {
				PlaceObj('RecipeIngredient', {
					'item', "MG42",
				}),
				PlaceObj('RecipeIngredient', {
					'item', "Combination_Kompositum58",
				}),
			},
			MechanicalRoll = true,
			ResultItems = {
				PlaceObj('RecipeIngredient', {
					'item', "MG58",
				}),
			},
			group = "Firearms",
			id = "MG42",
		}),
		PlaceObj('ModItemRecipeDef', {
			Difficulty = 80,
			ExplosivesRoll = true,
			Ingredients = {
				PlaceObj('RecipeIngredient', {
					'item', "Machete",
				}),
				PlaceObj('RecipeIngredient', {
					'item', "Combination_Kompositum58",
				}),
			},
			MechanicalRoll = true,
			ResultItems = {
				PlaceObj('RecipeIngredient', {
					'item', "Machete_Crafted",
				}),
			},
			group = "MeleeWeapon",
			id = "Machete_Crafted",
		}),
		PlaceObj('ModItemRecipeDef', {
			Difficulty = 80,
			Ingredients = {
				PlaceObj('RecipeIngredient', {
					'item', "Medkit",
				}),
				PlaceObj('RecipeIngredient', {
					'item', "Combination_Kompositum58",
				}),
			},
			ResultItems = {
				PlaceObj('RecipeIngredient', {
					'item', "Reanimationsset",
				}),
			},
			group = "Other",
			id = "Reanimationsset",
		}),
		PlaceObj('ModItemRecipeDef', {
			Difficulty = 70,
			Ingredients = {
				PlaceObj('RecipeIngredient', {
					'item', "Crowbar",
				}),
				PlaceObj('RecipeIngredient', {
					'item', "Combination_Kompositum58",
				}),
			},
			MechanicalRoll = true,
			ResultItems = {
				PlaceObj('RecipeIngredient', {
					'item', "PlasmaGun_Crowbar",
				}),
			},
			group = "Other",
			id = "PlasmaGun_Crowbar",
		}),
		}),
}