return PlaceObj('ModDef', {
	'title', "Enhanced Kompositum",
	'description', "[h1]Enhanced Kompositum[/h1]\n[h3]Features[/h3]\n[list]\n    [*]Increases all Damage reduction stats of the armor (including its category)\n    [*]Add new recipes to craft quest reward related items\n [/list]\n[h3]Mechanics[/h3] \n[list]\n    [*]Super-heavy penetration still crits on all types of armor\n    [*]It only affects armor crafted with Kompositum\n[/list]\n\n[h3]Kompositum Enhanced Recipes[/h3]\n[i]Always 1 combination Kompositum[/i]\n[list]\n    [*]Winchester = Confidante\n    [*]Auto5 = mabaxter\n    [*]M24 = Golden Gun\n    [*]Galil = The Hired Gun\n    [*]MG42 = MG58\n    [*]Medkit = Reanimation Kit\n    [*]Machete = Composite Machete\n    [*]Crowbar = PlasmaGun\n[/list]\n[hr][/hr]\n[h3]Related Mods[/h3]\n[list]\n	[*][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3253641552] Vanilla Battles Enhanced [/url]\n	[*][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3238563037] Diamond Briefcase Enhanced [/url]\n	[*][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3238546616] Random Attack [/url]\n	[*][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3238572469] Vanilla Weapons Expanded - Quest Items [/url]\n[/list]\n\n\n[url=https://ko-fi.com/sirni] You can support me here, or just see my funny face.[/url]",
	'image', "Mod/Tsa4PcG/Images/Screenshot 2024-04-13 164150.png",
	'last_changes', "- updated description",
	'dependencies', {},
	'id', "EnhancedK58",
	'author', "Sir Ni",
	'version_major', 1,
	'version_minor', 1,
	'version', 35,
	'lua_revision', 233360,
	'saved_with_revision', 350233,
	'code', {
		"InventoryItem/CamoArmor_Light_Kompositum.lua",
		"InventoryItem/CamoArmor_Medium_Kompositum.lua",
		"InventoryItem/FlakArmor_Kompositum.lua",
		"InventoryItem/FlakLeggings_Kompositum.lua",
		"InventoryItem/FlakVest_Kompositum.lua",
		"InventoryItem/HeavyArmorChestplate_Kompositum.lua",
		"InventoryItem/HeavyArmorHelmet_Kompositum.lua",
		"InventoryItem/HeavyArmorLeggings_Kompositum.lua",
		"InventoryItem/HeavyArmorTorso_Kompositum.lua",
		"InventoryItem/KevlarChestplate_Kompositum.lua",
		"InventoryItem/KevlarHelmet_Kompositum.lua",
		"InventoryItem/KevlarLeggings_Kompositum.lua",
		"InventoryItem/KevlarVest_Kompositum.lua",
		"InventoryItem/LightHelmet_Kompositum.lua",
	},
	'default_options', {},
	'has_data', true,
	'saved', 1726667776,
	'code_hash', 4913441837459482192,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "CamoArmor_Light_Kompositum",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "CamoArmor_Medium_Kompositum",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "FlakArmor_Kompositum",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "FlakLeggings_Kompositum",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "FlakVest_Kompositum",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "HeavyArmorChestplate_Kompositum",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "HeavyArmorHelmet_Kompositum",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "HeavyArmorLeggings_Kompositum",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "HeavyArmorTorso_Kompositum",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "KevlarChestplate_Kompositum",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "KevlarHelmet_Kompositum",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "KevlarLeggings_Kompositum",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "KevlarVest_Kompositum",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "LightHelmet_Kompositum",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "RecipeDef",
			'Id', "Winchester",
			'ClassDisplayName', "Combine recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "RecipeDef",
			'Id', "Auto5",
			'ClassDisplayName', "Combine recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "RecipeDef",
			'Id', "Galil",
			'ClassDisplayName', "Combine recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "RecipeDef",
			'Id', "M24",
			'ClassDisplayName', "Combine recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "RecipeDef",
			'Id', "MG42",
			'ClassDisplayName', "Combine recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "RecipeDef",
			'Id', "Machete_Crafted",
			'ClassDisplayName', "Combine recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "RecipeDef",
			'Id', "Reanimationsset",
			'ClassDisplayName', "Combine recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "RecipeDef",
			'Id', "PlasmaGun_Crowbar",
			'ClassDisplayName', "Combine recipe",
		}),
	},
	'steam_id', "3238744119",
	'TagWeapons&Items', true,
})